name: run-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Configurar JDK 17 (puedes cambiar a la versión que prefieras)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Puedes elegir otra distribución como zulu, adopt, etc.
        java-version: '17'

    # Paso 3: Ejecutar la compilación y los tests de Maven
    - name: Build with Maven
      run: mvn clean install